apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "pingaccess.name" . }}
    helm.sh/chart: {{ include "pingaccess.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "pingaccess.fullname" . }}-env-vars
data:
  PING_IDENTITY_ACCEPT_EULA: {{ .Values.license.acceptEULA | quote  }}
  PA_LOG_LEVEL: {{ .Values.pingaccess.logging | quote }}
{{ toYaml .Values.pingaccess.envs | indent 2 }}