apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pingaccess.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pingaccess.name" . }}
    helm.sh/chart: {{ include "pingaccess.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1 #{{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pingaccess.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pingaccess.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ if not .Values.license.useDevOpsKey }}
        volumeMounts:
        - name: license
          mountPath: /opt/in/instance/conf/pingaccess.lic
          subPath: pingaccess.lic
        {{ end -}}
        ports:
        {{- if or (and (.Values.pingaccess.clustering.enabled) (.Values.pingaccess.clustering.adminConsoleRole)) (not .Values.pingaccess.clustering.enabled) }}
        - containerPort: {{ .Values.service.admin.port }}
          name: {{ .Values.service.admin.name }}
        {{ end -}}
        {{- if or (and (.Values.pingaccess.clustering.enabled) (not .Values.pingaccess.clustering.adminConsoleRole)) (not .Values.pingaccess.clustering.enabled) }}
        - containerPort: {{ .Values.service.engine.port }}
          name: {{ .Values.service.engine.name }}
        {{ end -}}
        {{- if and (.Values.pingaccess.clustering.enabled) (.Values.pingaccess.clustering.adminConsoleRole) }}
        - containerPort: {{ .Values.pingaccess.clustering.service.cluster.port }}
          name: {{ .Values.pingaccess.clustering.service.cluster.name }}
        {{ end -}}
        envFrom:
        - configMapRef:
            name: {{ include "pingaccess.fullname" . }}-env-vars
        - secretRef:
            name: {{ include "pingaccess.fullname" . }}-devops-secret
            optional: true
        - secretRef:
            name: {{ include "pingaccess.fullname" . }}-git-secret
            optional: true
        readinessProbe:
          exec:
            command: [ {{ .Values.image.readinessCommand }} ]
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          exec:
            command: [ {{ .Values.image.livenessCommand }} ]
          initialDelaySeconds: 30
          periodSeconds: 30
    {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if not .Values.license.useDevOpsKey }}
      volumes:
      - name: license
        secret:
          secretName: {{ .Values.license.licenseSecretName }}
    {{- end }}